version: "3.9"
services:
  mysqldb:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=a123
      - MYSQL_DATABASE=todolist
    volumes:
      - db:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d

  service-todolist:
    build:
      context: .
    ports:
      - "8400:8400"
    environment:
      SPRING_APPLICATION_JSON: '{
            "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/todolist?allowPublicKeyRetrieval=true&useSSL=false",
            "spring.datasource.username" : "root",
            "spring.datasource.password" : "a123"
          }'
    depends_on:
      - mysqldb

volumes:
  db: