spring:
  datasource:
    url: jdbc:mysql://mysqldb:3306/todolist?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
    username: root
    password: a123
  application:
    name: todo-list
springdoc:
  api-docs:
    path: /todo-list/docs
  swagger-ui:
    path: /todo-list/api-docs/
server:
  port: 8400