spring:
  datasource:
    url: jdbc:mysql://localhost:3306/todolist?useSSL=false
    username: root
    password: a123
  application:
    name: todo-list
springdoc:
  api-docs:
    path: /todo-list/docs
  swagger-ui:
    path: /todo-list/api-docs/
server:
  port: 8400